# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: celery-worker
#   labels:
#     app: celery-worker
# spec:
#   selector:
#     matchLabels:
#       app: celery-worker
#   progressDeadlineSeconds: 900
#   template:
#     metadata:
#       labels:
#         app: celery-worker
#     spec:
#       containers:
#       - name: celery-worker
#         image: deiva2/celery-rabbitmq-poc:latest
#         imagePullPolicy: Always
#       #   startupProbe:
#       #     exec:
#       #       command: ["/bin/bash", "-c", "celery -q -A app inspect -d celery@$HOSTNAME --timeout 10 ping"]
#       #     initialDelaySeconds: 20
#       #     timeoutSeconds: 10
#       #     successThreshold: 1
#       #     failureThreshold: 30
#       #     periodSeconds: 10
#       #   readinessProbe:
#       #     exec:
#       #       command: ["/bin/bash", "-c", "celery -q -b $CELERY_BROKER_URL inspect -d celery@$HOSTNAME --timeout 10 ping"]
#       #     periodSeconds: 120
#       #     timeoutSeconds: 10
#       #     successThreshold: 1
#       #     failureThreshold: 3
#       #   livenessProbe:
#       #     exec:
#       #       command: ["/bin/bash", "-c", "celery -q -b $CELERY_BROKER_URL inspect -d celery@$HOSTNAME --timeout 10 ping"]
#       #     periodSeconds: 120
#       #     timeoutSeconds: 10
#       #     successThreshold: 1
#       #     failureThreshold: 5
#       #   resources:
#       #     requests:
#       #       memory: "384Mi"
#       #       cpu: "250m"
#       #     limits:
#       #       memory: "1Gi"
#       #       cpu: "500m"
#       # terminationGracePeriodSeconds: 2400

apiVersion: v1
kind: Pod
metadata:
  name: celery-pod
  namespace: default
  labels:
    name: celery-pod

spec:
  containers:
  - name: celery-pod
    image: deiva2/celery-rabbitmq-poc:latest
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 1
        memory: 512Mi