version: '2'
services:
    # rabbit:
    #     hostname: rabbit
    #     image: rabbitmq:latest
    #     environment:
    #         - RABBITMQ_DEFAULT_USER=test
    #         - RABBITMQ_DEFAULT_PASS=test
    #     ports:
    #         - "5672:5672"

    worker:
        # build:
        #     context: .
        #     dockerfile: dockerfile
        image: deiva2/celery-rabbitmq-poc:latest
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
        # command: -A test_celery.celery_poc worker --concurrency=20 --loglevel=info
        # deploy:
        #     replicas: 5
    
